# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UUhvDtALfTrE5QbiFrPeeWc3BaCXcU1p
"""

import streamlit as st
import yfinance as yf
import pandas_ta as ta
import pandas as pd
import plotly.graph_objects as go
from datetime import datetime
import pytz

# 設定網頁標題與圖示
st.set_page_config(page_title="2026 AI 股價偵測引擎", layout="wide")

# --- 側邊欄：參數設定 ---
st.sidebar.header("⚙️ 偵測參數設定")
stock_list = st.sidebar.text_input("輸入股票代號 (多支請用逗號隔開)", "1301.TW, 1303.TW, 2408.TW, 8046.TW, 2330.TW")
rsi_period = st.sidebar.slider("RSI 天數", 5, 30, 14)
vol_factor = st.sidebar.slider("量增倍數門檻", 1.0, 5.0, 2.5)

# --- 主畫面：標題與時間 ---
tw_tz = pytz.timezone('Asia/Taipei')
now = datetime.now(tw_tz)

st.title("🚀 專業級強勢突破偵測系統")
col_time1, col_time2 = st.columns(2)
col_time1.metric("📅 偵測日期", now.strftime('%Y-%m-%d'))
col_time2.metric("⏰ 台北時間", now.strftime('%H:%M:%S'))

st.markdown("---")

# --- 核心邏輯 ---
stocks = [s.strip() for s in stock_list.split(",")]

if st.button("🔍 開始全量掃描"):
    for symbol in stocks:
        with st.expander(f"📊 檢查 {symbol} 的詳細分析", expanded=True):
            try:
                # 抓取數據
                df = yf.download(symbol, period="60d", interval="1d", progress=False)
                if df.empty:
                    st.error(f"找不到 {symbol} 的數據")
                    continue

                # 指標計算
                df['RSI'] = ta.rsi(df['Close'].squeeze(), length=rsi_period)
                avg_vol = df['Volume'].iloc[-6:-1].mean().values[0]
                curr_vol = df['Volume'].iloc[-1].values[0]
                curr_price = df['Close'].iloc[-1].values[0]
                vol_ratio = curr_vol / avg_vol

                # 顯示數據卡片
                c1, c2, c3 = st.columns(3)
                c1.metric("目前股價", f"{curr_price:.2f}")
                c2.metric("成交量倍數", f"{vol_ratio:.2f}x", delta=f"{vol_ratio-1:.2f}")
                c3.metric("RSI 指數", f"{df['RSI'].iloc[-1]:.1f}")

                # 判定狀態
                if vol_ratio >= vol_factor:
                    st.success(f"🚩 訊號確認：{symbol} 出現爆量突破！")
                else:
                    st.info(f"⚪ {symbol} 趨勢尚在整理中。")

# 繪製 K 線圖
                fig = go.Figure(data=[go.Candlestick(x=df.index,
                                open=df['Open'], high=df['High'],
                                low=df['Low'], close=df['Close'], name='K線')])
                fig.update_layout(height=400, margin=dict(l=0, r=0, t=0, b=0))
                st.plotly_chart(fig, use_container_width=True)
                
            except Exception as e:
                st.warning(f"分析 {symbol} 時出錯: {e}")

st.sidebar.markdown("---")
st.sidebar.write("💡 提示：輸入代號請加 .TW (台股)")
